### ISSUE TITLE
Different resolution?

### ISSUE THREAD

**Issue by federicocunico** [ifzhang/FairMOT#181]
First of all, thanks for the amazing job, I love it.
I was able to run the code with default demo, and wanted to try to run the demo with different resolution than default image size value ( 1088, 608 ). 
Is (1088, 608) the only supported resolution? What are the other supported resolutions? Do they follow some rule?

Thank you

**Comment by alberto139** [comment]
Hi @federicocunico,
I'm currently facing the same issue. 

I'm running the demo.py using:
```
python3 demo.py mot --load_model ../models/all_hrnet_v2_w18.pth --arch hrnet_18 --reid_dim 128 --conf_thres 0.4
```

I've tried changing all the instances of (1088, 608) to (640, 360) with no luck. I always get the following error:
```
src/lib/models/networks/pose_hrnet.py", line 260, in forward
    y = y + self.fuse_layers[i][j](x[j])
RuntimeError: The size of tensor a (90) must match the size of tensor b (92) at non-singleton dimension 2
``` 

This leads me to think that the problem is whit the `pose_hrnet` model. I haven't tried with any other model backbone.

@ifzhang commented on #174 to change `opts.py` but I think that issue was only concerned with training.

**Comment by ifzhang** [comment]
The resolution should be multiples of 32. 864x480 and 576x320 are OK. The results of 864x480 do not decrease much and it can get 40+ FPS.
