### ISSUE TITLE
Confusion in jde.py

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/FairMOT#90]
Hi, i found track id start from index 1 in gen_labels_15.py, but in jde.py the track number also +1 in filed track id([1]) of the label( self.tid_num[ds] = max_index + 1):
        for ds, label_paths in self.label_files.items():
            max_index = -1

            for lp in label_paths:
                lb = np.loadtxt(lp)
                if len(lb) < 1:  
                    continue

                if len(lb.shape) < 2:  
                    img_max = lb[1]
                else:
                    img_max = np.max(lb[:, 1])
                if img_max > max_index:
                    max_index = img_max

            self.tid_num[ds] = max_index + 1
Is this correct? 
And the variable img_max is also cofusing, it should be track_max? Am i right?

**Comment by ifzhang** [comment]
Yes! If id starts from 1, then do not need to +1. The variable img_max can be named id_max or track_max better. The ids are not that important because we just want to separate people with different ids during training and we do not need the ids during testing. So the real number of the id is not that important.

**Comment by CaptainEven** [comment]
@ifzhang Thanks for replying!
